backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

# These lines should *not* be indented
media_folder: "public/public/assets/images" # Media files will be stored in the repo under static/images/uploads
public_folder: "public/assets/images" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., title.md
    fields: # The fields for each document, usually in front matter
      - {label: "title", name: "title", widget: "string"}
      - {label: "category", name: "category", widget: "string"}
      - {label: "date", name: "createdAt", widget: "datetime"}
      - {label: "Image", name: "cover", widget: "image", required: false}
      - {label: "author", name: "author", widget: "string", required: false}
      - {label: "description", name: "description", widget: "markdown"} 

  - name: "bulletin" # Used in routes, e.g., /admin/collections/blog
    label: "Bulletin" # Used in the UI
    folder: "bulletin" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., title.md
    fields: # The fields for each document, usually in front matter
      - {label: "month", name: "title", widget: "string"}
      - {label: "Image", name: "img", widget: "image", required: true}
      - {label: "file", name: "file", widget: "file", required: true}
    
  - name: "gallery" # Used in routes, e.g., /admin/collections/blog
    label: "Gallery" # Used in the UI
    folder: "gallery" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., title.md
    fields: # The fields for each document, usually in front matter
      - {label: "title", name: "title", widget: "string"}
      - {label: "Gallery", name: "Images", widget: "list", field: {label: Image, name: image, widget: image}}

  - name: "popup" # Used in routes, e.g., /admin/collections/blog
    label: "PopUp" # Used in the UI
    folder: "popup" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Image", name: "cover", widget: "image", required: false}
